<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('daily_forecasts', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string("location");
            $table->string("date")->nullable();
            $table->string("time")->nullable();
            $table->string('local_datetime')->nullable();
            $table->date('local_date')->nullable();
            $table->string('local_time')->nullable();
            $table->string('timezone')->nullable();
            $table->float("altimeterSettingAvg")->nullable();
            $table->float("altimeterSettingMax")->nullable();
            $table->float("altimeterSettingMin")->nullable();
            $table->float("cloudBaseAvg")->nullable();
            $table->float("cloudBaseMax")->nullable();
            $table->float("cloudBaseMin")->nullable();
            $table->float("cloudCeilingAvg")->nullable();
            $table->float("cloudCeilingMax")->nullable();
            $table->float("cloudCeilingMin")->nullable();
            $table->float("cloudCoverAvg")->nullable();
            $table->float("cloudCoverMax")->nullable();
            $table->float("cloudCoverMin")->nullable();
            $table->float("dewPointAvg")->nullable();
            $table->float("dewPointMax")->nullable();
            $table->float("dewPointMin")->nullable();
            $table->float("evapotranspirationAvg")->nullable();
            $table->float("evapotranspirationMax")->nullable();
            $table->float("evapotranspirationMin")->nullable();
            $table->float("evapotranspirationSum")->nullable();
            $table->float("freezingRainIntensityAvg")->nullable();
            $table->float("freezingRainIntensityMax")->nullable();
            $table->float("freezingRainIntensityMin")->nullable();
            $table->float("humidityAvg")->nullable();
            $table->float("humidityMax")->nullable();
            $table->float("humidityMin")->nullable();
            $table->float("iceAccumulationAvg")->nullable();
            $table->float("iceAccumulationLweAvg")->nullable();
            $table->float("iceAccumulationLweMax")->nullable();
            $table->float("iceAccumulationLweMin")->nullable();
            $table->float("iceAccumulationLweSum")->nullable();
            $table->float("iceAccumulationMax")->nullable();
            $table->float("iceAccumulationMin")->nullable();
            $table->float("iceAccumulationSum")->nullable();
            $table->date("moonriseTime")->nullable();
            $table->date("moonsetTime")->nullable();
            $table->float("precipitationProbabilityAvg")->nullable();
            $table->float("precipitationProbabilityMax")->nullable();
            $table->float("precipitationProbabilityMin")->nullable();
            $table->float("pressureSeaLevelAvg")->nullable();
            $table->float("pressureSeaLevelMax")->nullable();
            $table->float("pressureSeaLevelMin")->nullable();
            $table->float("pressureSurfaceLevelAvg")->nullable();
            $table->float("pressureSurfaceLevelMax")->nullable();
            $table->float("pressureSurfaceLevelMin")->nullable();
            $table->float("rainAccumulationAvg")->nullable();
            $table->float("rainAccumulationMax")->nullable();
            $table->float("rainAccumulationMin")->nullable();
            $table->float("rainAccumulationSum")->nullable();
            $table->float("rainIntensityAvg")->nullable();
            $table->float("rainIntensityMax")->nullable();
            $table->float("rainIntensityMin")->nullable();
            $table->float("sleetAccumulationAvg")->nullable();
            $table->float("sleetAccumulationLweAvg")->nullable();
            $table->float("sleetAccumulationLweMax")->nullable();
            $table->float("sleetAccumulationLweMin")->nullable();
            $table->float("sleetAccumulationLweSum")->nullable();
            $table->float("sleetAccumulationMax")->nullable();
            $table->float("sleetAccumulationMin")->nullable();
            $table->float("sleetIntensityAvg")->nullable();
            $table->float("sleetIntensityMax")->nullable();
            $table->float("sleetIntensityMin")->nullable();
            $table->float("snowAccumulationAvg")->nullable();
            $table->float("snowAccumulationLweAvg")->nullable();
            $table->float("snowAccumulationLweMax")->nullable();
            $table->float("snowAccumulationLweMin")->nullable();
            $table->float("snowAccumulationLweSum")->nullable();
            $table->float("snowAccumulationMax")->nullable();
            $table->float("snowAccumulationMin")->nullable();
            $table->float("snowAccumulationSum")->nullable();
            $table->float("snowDepthAvg")->nullable();
            $table->float("snowDepthMax")->nullable();
            $table->float("snowDepthMin")->nullable();
            $table->float("snowDepthSum")->nullable();
            $table->float("snowIntensityAvg")->nullable();
            $table->float("snowIntensityMax")->nullable();
            $table->float("snowIntensityMin")->nullable();
            $table->date("sunriseTime")->nullable();
            $table->date("sunsetTime")->nullable();
            $table->float("temperatureApparentAvg")->nullable();
            $table->float("temperatureApparentMax")->nullable();
            $table->float("temperatureApparentMin")->nullable();
            $table->float("temperatureAvg")->nullable();
            $table->float("temperatureMax")->nullable();
            $table->float("temperatureMin")->nullable();
            $table->float("uvHealthConcernAvg")->nullable();
            $table->float("uvHealthConcernMax")->nullable();
            $table->float("uvHealthConcernMin")->nullable();
            $table->float("uvIndexAvg")->nullable();
            $table->float("uvIndexMax")->nullable();
            $table->float("uvIndexMin")->nullable();
            $table->float("visibilityAvg")->nullable();
            $table->float("visibilityMax")->nullable();
            $table->float("visibilityMin")->nullable();
            $table->float("weatherCodeMax")->nullable();
            $table->float("weatherCodeMin")->nullable();
            $table->float("windDirectionAvg")->nullable();
            $table->float("windGustAvg")->nullable();
            $table->float("windGustMax")->nullable();
            $table->float("windGustMin")->nullable();
            $table->float("windSpeedAvg")->nullable();
            $table->float("windSpeedMax")->nullable();
            $table->float("windSpeedMin")->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('daily_forecasts');
    }
};
